### ISSUE TITLE
Use real configuration file instead of Package.swift code

### ISSUE THREAD

**Issue by Dschee** [shibapm/Komondor#19]
The README doesn't really explain, why the configuration of the commits has to be done within Package.swift and I find it very confusing and misplaced there. To me, the example configuration looks like it should actually be just a configuration file (using `YAML`, `TOML` or whatever you prefer) like this (`komondor.yml`):

```yaml
pre-push: swift test
pre-commit":
  - swift test
  - swift run swiftFormat .
  - swift run swiftlint autocorrect --path Sources/
  - git add .
```

I feel like that would be much cleaner. But feel free to explain, why you opted for the current solution. Maybe I don't see the whole picture ...
